[package]
name = "child"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
common_dep = { path = "../common_dep" }

[build-dependencies]
common_dep = { path = "../common_dep", features = [ "std" ] }
